# Generated by Django 3.1.2 on 2020-10-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quackerprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quackerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
